// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SalesService.Data;

#nullable disable

namespace SalesService.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20251125153000_RenameOrderItemIdToOrderItemID")]
    partial class RenameOrderItemIdToOrderItemID
    {
    }
}
